export const CAMPUSES = [
  'Rice University',
  'University of Houston',
  'Houston Community College',
  'Texas Southern University',
  'University of St. Thomas (Houston)',
  'University of Houston Downtown',
  'Houston Baptist University',
  'Sam Houston State University',
  'Texas A&M University',
  'Texas A&M University - Galveston',
  'Baylor College of Medicine',
  'University of Texas Health Science Center',
  'University of Texas at Austin',
  'Texas State University',
  'University of North Texas',
  'University of Texas at Dallas',
  'University of Texas at San Antonio',
  'Texas Tech University',
  'Texas Christian University',
  'Baylor University',
  'Southern Methodist University',
  'Tulane University',
  'Louisiana State University',
  'University of Florida',
  'Florida State University',
  'University of Georgia',
  'Georgia Institute of Technology',
  'University of Alabama',
  'Auburn University',
  'University of North Carolina at Chapel Hill',
  'North Carolina State University',
  'Duke University',
  'Vanderbilt University',
  'University of Tennessee',
  'University of South Carolina',
  'Virginia Tech',
  'University of Virginia',
  'Pennsylvania State University',
  'Ohio State University',
  'University of Michigan',
  'Michigan State University',
  'Purdue University',
  'Indiana University',
  'University of Illinois Urbana-Champaign',
  'University of Wisconsin-Madison',
  'University of Minnesota',
  'University of Colorado Boulder',
  'Arizona State University',
  'University of Arizona',
  'University of Washington',
  'University of Oregon',
  'Stanford University',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of Southern California',
  'New York University',
  'Columbia University',
  'Cornell University',
  'Boston University',
  'Northeastern University',
  'Harvard University',
  'Massachusetts Institute of Technology',
];

export const CITIES = [
  'Houston',
  'Sugar Land',
  'The Woodlands',
  'Katy',
  'Pearland',
  'Bellaire',
  'Pasadena',
  'League City',
  'Galveston',
  'College Station',
  'Austin',
  'Dallas',
  'San Antonio',
  'Fort Worth',
  'El Paso',
  'Phoenix',
  'Los Angeles',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Seattle',
  'Portland',
  'Denver',
  'Chicago',
  'Minneapolis',
  'St. Louis',
  'Atlanta',
  'Miami',
  'Orlando',
  'Tampa',
  'Nashville',
  'New Orleans',
  'Charlotte',
  'Raleigh',
  'Washington, DC',
  'Philadelphia',
  'New York',
  'Boston',
];

export function getLocationOptions(type: 'campus' | 'city', query: string) {
  const list = type === 'campus' ? CAMPUSES : CITIES;
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter((name) => name.toLowerCase().includes(q));
}
