export {
  createAccountWithEmail,
  deleteAccountAndData,
  ensureFirebase,
  getCurrentFirebaseUser,
  getFirebaseConfigStatus,
  getFirebaseInitError,
  isFirebaseConfigured,
  observeAuthStateChanges,
  observeIdTokenChanges,
  reauthenticateCurrentUser,
  sendVerificationEmail,
  seedCachedIdToken,
  sendPasswordResetEmail,
  signInWithEmail,
  signOutCurrentUser,
  updateCurrentUserPassword,
} from '../firebaseClient';
